In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Preprocessing

In [47]:
result = pd.read_csv("../results/time_preprocessing.csv")
result.T

                                                          0
Pipeline                                            Unknown
model                                               Unknown
Building multimodal index: sliding_window         1526.6412
Building multimodal index: semantic               1457.9792
Building multimodal index: hierarchical            1511.678
Building multimodal index: enhanced_hierarchical   1640.878
Total Pipeline Runtime                            6137.1765

## Metric/results

In [46]:
result = pd.read_csv("../results/pipeline_results.csv")
important_cols = ["Pipeline","Test Size","LLM Model","Embedding Model","precision@5", "recall@5", "exact_match", "token_f1"]
display(pd.DataFrame(result[important_cols].iloc[0]))

                                                0
Pipeline         1_Baseline (BaselineRAGPipeline)
Test Size                                     150
LLM Model                    qwen3-vl:8b-instruct
Embedding Model               jinaai/jina-clip-v2
precision@5                                0.1267
recall@5                                   0.6333
exact_match                                  0.12
token_f1                                   0.1593

In [39]:
result = pd.read_csv("../results/pipeline_results.csv")
important_cols = ["Pipeline","Test Size","LLM Model","Embedding Model","precision@5", "recall@5", "exact_match", "token_f1"]
display(result[important_cols])

,Pipeline,Test Size,LLM Model,Embedding Model,precision@5,recall@5,exact_match,token_f1
0,1_Baseline (BaselineRAGPipeline),150,qwen3-vl:8b-instruct,jinaai/jina-clip-v2,0.1267,0.6333,0.12,0.1593
1,2_Chunk_Ablation_sliding_window (AdvancedRAGPi...,150,qwen3-vl:8b-instruct,jinaai/jina-clip-v2,0.1827,0.9133,0.1333,0.1922
2,2_Chunk_Ablation_semantic (AdvancedRAGPipeline),150,qwen3-vl:8b-instruct,jinaai/jina-clip-v2,0.1827,0.9133,0.12,0.1719
3,2_Chunk_Ablation_hierarchical (AdvancedRAGPipe...,150,qwen3-vl:8b-instruct,jinaai/jina-clip-v2,0.1827,0.9133,0.1133,0.1677
4,2_Chunk_Ablation_enhanced_hierarchical (Advanc...,150,qwen3-vl:8b-instruct,jinaai/jina-clip-v2,0.1827,0.9133,0.0933,0.1479
5,3_Query_Ablation_multi_query (AdvancedRAGPipel...,150,qwen3-vl:8b-instruct,jinaai/jina-clip-v2,0.1773,0.8867,0.1333,0.1992
6,3_Query_Ablation_rag_fusion (AdvancedRAGPipeline),150,qwen3-vl:8b-instruct,jinaai/jina-clip-v2,0.1733,0.8667,0.1333,0.1939
7,3_Query_Ablation_step_back (AdvancedRAGPipeline),150,qwen3-vl:8b-instruct,jinaai/jina-clip-v2,0.1747,0.8733,0.1267,0.1827
8,3_Query_Ablation_hyde (AdvancedRAGPipeline),150,qwen3-vl:8b-instruct,jinaai/jina-clip-v2,0.152,0.76,0.0733,0.1371
9,3_Query_Ablation_query_decomposition (Advanced...,150,qwen3-vl:8b-instruct,jinaai/jina-clip-v2,0.176,0.88,0.1333,0.1882
10,3_Query_Ablation_query_rewriting (AdvancedRAGP...,150,qwen3-vl:8b-instruct,jinaai/jina-clip-v2,0.184,0.92,0.12,0.1683
11,3_Query_Ablation_query_expansion (AdvancedRAGP...,150,qwen3-vl:8b-instruct,jinaai/jina-clip-v2,0.1773,0.8867,0.12,0.1869
12,4_Prompt_Ablation_few_shot (AdvancedRAGPipeline),150,qwen3-vl:8b-instruct,jinaai/jina-clip-v2,0.184,0.92,0.0933,0.1515
13,4_Prompt_Ablation_role (AdvancedRAGPipeline),150,qwen3-vl:8b-instruct,jinaai/jina-clip-v2,0.184,0.92,0.08,0.1381
14,4_Prompt_Ablation_cot (AdvancedRAGPipeline),150,qwen3-vl:8b-instruct,jinaai/jina-clip-v2,0.184,0.92,0.1667,0.207
15,5_Multimodal_True (AdvancedRAGPipeline),150,qwen3-vl:8b-instruct,jinaai/jina-clip-v2,0.1787,0.8933,0.1333,0.1739
16,Pipeline,Test Size,LLM Model,Embedding Model,precision@5,recall@5,exact_match,token_f1
17,Step1_ChunkOpt_fixed_size (AdvancedRAGPipeline),150,qwen3-vl:8b-instruct,jinaai/jina-clip-v2,0.184,0.92,0.1267,0.1893
18,Step1_ChunkOpt_sliding_window (AdvancedRAGPipe...,150,qwen3-vl:8b-instruct,jinaai/jina-clip-v2,0.1827,0.9133,0.1333,0.1922
19,Step1_ChunkOpt_semantic (AdvancedRAGPipeline),150,qwen3-vl:8b-instruct,jinaai/jina-clip-v2,0.1827,0.9133,0.12,0.1719
20,Step1_ChunkOpt_hierarchical (AdvancedRAGPipeline),150,qwen3-vl:8b-instruct,jinaai/jina-clip-v2,0.1827,0.9133,0.1133,0.1677
21,Step1_ChunkOpt_enhanced_hierarchical (Advanced...,150,qwen3-vl:8b-instruct,jinaai/jina-clip-v2,0.1827,0.9133,0.0933,0.1479
22,Step2_QueryOpt_standard (AdvancedRAGPipeline),150,qwen3-vl:8b-instruct,jinaai/jina-clip-v2,0.1827,0.9133,0.1333,0.1922
23,Step2_QueryOpt_multi_query (AdvancedRAGPipeline),150,qwen3-vl:8b-instruct,jinaai/jina-clip-v2,0.1787,0.8933,0.14,0.1965
24,Step2_QueryOpt_rag_fusion (AdvancedRAGPipeline),150,qwen3-vl:8b-instruct,jinaai/jina-clip-v2,0.176,0.88,0.1467,0.2016
25,Step2_QueryOpt_step_back (AdvancedRAGPipeline),150,qwen3-vl:8b-instruct,jinaai/jina-clip-v2,0.176,0.88,0.1267,0.1741
26,Step2_QueryOpt_hyde (AdvancedRAGPipeline),150,qwen3-vl:8b-instruct,jinaai/jina-clip-v2,0.148,0.74,0.08,0.1354
27,Step2_QueryOpt_query_decomposition (AdvancedRA...,150,qwen3-vl:8b-instruct,jinaai/jina-clip-v2,0.1747,0.8733,0.1267,0.1857
28,Step2_QueryOpt_query_rewriting (AdvancedRAGPip...,150,qwen3-vl:8b-instruct,jinaai/jina-clip-v2,0.1827,0.9133,0.1467,0.2004
29,Step2_QueryOpt_query_expansion (AdvancedRAGPip...,150,qwen3-vl:8b-instruct,jinaai/jina-clip-v2,0.1707,0.8533,0.1,0.1627
30,Step3_PromptOpt_standard (AdvancedRAGPipeline),150,qwen3-vl:8b-instruct,jinaai/jina-clip-v2,0.176,0.88,0.1467,0.2016
31,Step3_PromptOpt_few_shot (AdvancedRAGPipeline),150,qwen3-vl:8b-instruct,jinaai/jina-clip-v2,0.176,0.88,0.1,0.1614
32,Step3_PromptOpt_role (AdvancedRAGPipeline),150,qwen3-vl:8b-instruct,jinaai/jina-clip-v2,0.176,0.88,0.1,0.153
33,Step3_PromptOpt_cot (AdvancedRAGPipeline),150,qwen3-vl:8b-instruct,jinaai/jina-clip-v2,0.176,0.88,0.1467,0.1878

## Pipeline time recorded

In [50]:
result = pd.read_csv("../results/pipeline_time.csv")
display(pd.DataFrame(result.iloc[0]))

                                                         0
Pipeline                  1_Baseline (BaselineRAGPipeline)
model                                 qwen3-vl:8b-instruct
Index Build/Load                                   45.8012
Component Initialization                            0.0158
Single Query Test                                   0.9621
Full Evaluation Time                               77.4237
Total Pipeline Runtime                            124.2028

In [45]:
result = pd.read_csv("../results/pipeline_time.csv")
result

,Pipeline,model,Index Build/Load,Component Initialization,Single Query Test,Full Evaluation Time,Total Pipeline Runtime
0,1_Baseline (BaselineRAGPipeline),qwen3-vl:8b-instruct,45.8012,0.0158,0.9621,77.4237,124.2028
1,2_Chunk_Ablation_sliding_window (AdvancedRAGPi...,qwen3-vl:8b-instruct,43.5951,0.0135,1.4864,241.9458,287.0409
2,2_Chunk_Ablation_semantic (AdvancedRAGPipeline),qwen3-vl:8b-instruct,52.1082,0.0158,1.3504,216.6868,270.1612
3,2_Chunk_Ablation_hierarchical (AdvancedRAGPipe...,qwen3-vl:8b-instruct,44.5680,0.0295,0.6080,111.0101,156.2155
4,2_Chunk_Ablation_enhanced_hierarchical (Advanc...,qwen3-vl:8b-instruct,57.4848,0.0197,1.9327,238.4471,297.8843
5,3_Query_Ablation_multi_query (AdvancedRAGPipel...,qwen3-vl:8b-instruct,50.5924,0.0177,1.7943,287.2127,339.6172
6,3_Query_Ablation_rag_fusion (AdvancedRAGPipeline),qwen3-vl:8b-instruct,50.4469,0.0212,1.8060,302.3411,354.6152
7,3_Query_Ablation_step_back (AdvancedRAGPipeline),qwen3-vl:8b-instruct,52.1548,0.0209,0.9022,190.0842,243.1620
8,3_Query_Ablation_hyde (AdvancedRAGPipeline),qwen3-vl:8b-instruct,50.1457,0.0191,0.7408,131.9696,182.8752
9,3_Query_Ablation_query_decomposition (Advanced...,qwen3-vl:8b-instruct,51.3524,0.0153,1.6245,299.6719,352.6641
10,3_Query_Ablation_query_rewriting (AdvancedRAGP...,qwen3-vl:8b-instruct,49.5442,0.0194,0.9312,172.7806,223.2753
11,3_Query_Ablation_query_expansion (AdvancedRAGP...,qwen3-vl:8b-instruct,50.2205,0.0232,1.5789,258.3494,310.1721
12,4_Prompt_Ablation_few_shot (AdvancedRAGPipeline),qwen3-vl:8b-instruct,51.5251,0.0167,0.6255,111.5888,163.7560
13,4_Prompt_Ablation_role (AdvancedRAGPipeline),qwen3-vl:8b-instruct,58.3860,0.0272,0.8716,111.7207,171.0056
14,4_Prompt_Ablation_cot (AdvancedRAGPipeline),qwen3-vl:8b-instruct,52.5619,0.0179,0.7344,113.4645,166.7798
15,5_Multimodal_True (AdvancedRAGPipeline),qwen3-vl:8b-instruct,49.3055,0.0303,0.5386,117.1804,167.0548
16,Step1_ChunkOpt_fixed_size (AdvancedRAGPipeline),qwen3-vl:8b-instruct,60.4031,0.0242,2.4129,342.2336,405.0737
17,Step1_ChunkOpt_sliding_window (AdvancedRAGPipe...,qwen3-vl:8b-instruct,93.4540,0.0415,2.2395,338.5685,434.3043
18,Step1_ChunkOpt_semantic (AdvancedRAGPipeline),qwen3-vl:8b-instruct,72.1510,0.0215,0.8277,119.1608,192.1613
19,Step1_ChunkOpt_hierarchical (AdvancedRAGPipeline),qwen3-vl:8b-instruct,50.7653,0.0212,0.7711,121.9211,173.4786
20,Step1_ChunkOpt_enhanced_hierarchical (Advanced...,qwen3-vl:8b-instruct,49.8105,0.0181,0.7816,137.2443,187.8545
21,Step2_QueryOpt_standard (AdvancedRAGPipeline),qwen3-vl:8b-instruct,48.4678,0.0177,0.7472,129.5720,178.8048
22,Step2_QueryOpt_multi_query (AdvancedRAGPipeline),qwen3-vl:8b-instruct,60.7957,0.0209,3.2213,468.2072,532.2457
23,Step2_QueryOpt_rag_fusion (AdvancedRAGPipeline),qwen3-vl:8b-instruct,52.3438,0.0194,2.8778,471.2670,526.5080
24,Step2_QueryOpt_step_back (AdvancedRAGPipeline),qwen3-vl:8b-instruct,52.0349,0.0197,1.8250,298.4499,352.3295
25,Step2_QueryOpt_hyde (AdvancedRAGPipeline),qwen3-vl:8b-instruct,49.1200,0.0154,1.5447,250.7620,301.4424
26,Step2_QueryOpt_query_decomposition (AdvancedRA...,qwen3-vl:8b-instruct,49.2211,0.0222,2.9132,464.2100,516.3689
27,Step2_QueryOpt_query_rewriting (AdvancedRAGPip...,qwen3-vl:8b-instruct,51.2904,0.0090,1.8834,302.1195,355.3023
28,Step2_QueryOpt_query_expansion (AdvancedRAGPip...,qwen3-vl:8b-instruct,50.2751,0.0162,3.3044,463.7478,517.3435
29,Step3_PromptOpt_standard (AdvancedRAGPipeline),qwen3-vl:8b-instruct,49.0640,0.0241,2.1425,361.7238,412.9566
30,Step3_PromptOpt_few_shot (AdvancedRAGPipeline),qwen3-vl:8b-instruct,54.8576,0.0206,3.1641,577.5591,635.6039
31,Step3_PromptOpt_role (AdvancedRAGPipeline),qwen3-vl:8b-instruct,49.3809,0.0174,2.8315,660.4900,712.7219
32,Step3_PromptOpt_cot (AdvancedRAGPipeline),qwen3-vl:8b-instruct,60.4913,0.0174,3.6746,701.5659,765.7492