In [20]:
import pandas as pd
from datetime import datetime
import os

hours_log = pd.read_csv("hours.csv")
hours_log["Date"] = pd.to_datetime(hours_log["Date"], format="%d.%m.%Y")
hours_log["Start"] = pd.to_datetime(hours_log["Start"], format="%H:%M")
hours_log["End"] = pd.to_datetime(hours_log["End"], format="%H:%M")
hours_log["Hours"] = (hours_log["End"] - hours_log["Start"]).dt.total_seconds() / 3600

# Summarize hours by contributor
summary = hours_log.groupby("Name")["Hours"].sum().reset_index()
summary = summary.sort_values(by="Hours", ascending=False)

# Summarize hours by tag
tag_summary = hours_log.groupby("Tag")["Hours"].sum().reset_index()
tag_summary = tag_summary.sort_values(by="Hours", ascending=False)

# Projected final hours calculation
project_start = datetime(2025, 9, 11)
project_end = datetime(2025, 11, 15)
last_log_day = hours_log["Date"].max()

days_passed = (last_log_day - project_start).days + 1  # include start day
total_days = (project_end - project_start).days + 1

# Estimate final hours per author
summary["Hours per day"] = summary["Hours"] / days_passed
summary["Estimated final hours"] = summary["Hours per day"] * total_days

print(f"{'=' * 10} {"Development Hours Report"} {'=' * 10}")
display("# Total Hours by Contributor:", summary)
display("# Total Hours by Tag:", tag_summary)

========== Development Hours Report ==========

'# Total Hours by Contributor:'

     Name  Hours  Hours per day  Estimated final hours
1  vaakir   3.75           3.75                  247.5
0  jon-tj   3.00           3.00                  198.0

'# Total Hours by Tag:'

                 Tag  Hours
1  Education & recap   3.75
0    Design Document   3.00